---
title: "Instacart Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```

```{r, include = FALSE}
data("instacart")

instacart = 
  instacart %>%
  as_tibble(instacart) %>%
  janitor::clean_names() %>%
  select(add_to_cart_order, order_dow, order_hour_of_day, aisle)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Plotly barplot

This barplot reveals number of items ordered in each aisle, limiting to aisles with more than 5000 items ordered.

```{r}
instacart %>%
  count(aisle) %>%
  filter(n > 5000) %>%
  mutate(
    aisle = fct_reorder(aisle, n),
    text_label = str_c("Aisle: ", aisle, "\nNumber of Orders: ", n)
  ) %>%
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar", text = ~text_label, colors = "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Plotly scatterplot

This scatterplot shows 1000 randomly selected samples' order hour of day for different types of Aisle sorted by weekday.

```{r}
instacart %>%
  sample_n(1000) %>%
  group_by(aisle) %>%
  mutate(text_label = str_c("Aisle: ", aisle, "\nOrder Time: ", order_hour_of_day, ":00")) %>%
  plot_ly(
    x = ~aisle, y = ~order_hour_of_day, type = "scatter", mode = "markers",
    color = ~order_dow, text = ~text_label, alpha = 0.5)
```

### Plotly boxplot

This boxplot indicates 1500 randomly selected samples' number of orders added to cart for each Aisle.

```{r}
instacart %>%
  sample_n(1500) %>%
  mutate(aisle = fct_reorder(aisle, add_to_cart_order)) %>%
  plot_ly(y = ~add_to_cart_order, color = ~aisle, type = "box", colors = "viridis")
```

